server:
  port: ${PORT}
spring:
  application:
    name: w2n-challenge-service
  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: none
              create-source: metadata
              create-target: src/main/resources/db/changelog/changes/db.quickstart.sql
  liquibase:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}