server:
  port: ${PORT}
spring:
  application:
    name: w2n-challenge-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    change-log: classpath:db/changelog/changelog.yaml