DROP TABLE IF EXISTS HEROES;
CREATE TABLE HEROES(ID INT PRIMARY KEY, NAME VARCHAR(255));

INSERT INTO HEROES (id, name) VALUES
(1, 'Spiderman'),
(2, 'Batman'),
(3, 'Superman'),
(4, 'Wonder Woman'),
(5, 'Captain America'),
(6, 'Iron Man'),
(7, 'Thor'),
(8, 'Hulk'),
(9, 'Black Widow'),
(10, 'Wolverine'),
(11, 'Deadpool'),
(12, 'Daredevil'),
(13, 'Doctor Strange'),
(14, 'Green Lantern'),
(15, 'Flash'),
(16, 'Aquaman'),
(17, 'Black Panther'),
(18, 'Cyclops'),
(19, 'Jean Grey'),
(20, 'Storm'),
(21, 'Beast'),
(22, 'Professor X'),
(23, 'Gambit'),
(24, 'Rogue'),
(25, 'Nightcrawler'),
(26, 'Colossus'),
(27, 'Shadowcat'),
(28, 'Silver Surfer'),
(29, 'Nova'),
(30, 'Ghost Rider'),
(31, 'Punisher'),
(32, 'Moon Knight'),
(33, 'Blade'),
(34, 'Green Arrow'),
(35, 'Hawkeye'),
(36, 'Vision'),
(37, 'Scarlet Witch'),
(38, 'Quicksilver'),
(39, 'Ant-Man'),
(40, 'Wasp'),
(41, 'Falcon'),
(42, 'War Machine'),
(43, 'Black Knight'),
(44, 'Mockingbird'),
(45, 'Captain Marvel'),
(46, 'Ms. Marvel'),
(47, 'Jessica Jones'),
(48, 'Luke Cage'),
(49, 'Iron Fist'),
(50, 'Dagger'),
(51, 'Cloak'),
(52, 'Hercules'),
(53, 'Namor'),
(54, 'Squirrel Girl'),
(55, 'Shang-Chi'),
(56, 'Mister Fantastic'),
(57, 'Invisible Woman'),
(58, 'Human Torch'),
(59, 'The Thing'),
(60, 'Silver Claw'),
(61, 'Wonder Man'),
(62, 'Hank Pym'),
(63, 'She-Hulk'),
(64, 'Spider-Woman'),
(65, 'Agent Venom'),
(66, 'Venom'),
(67, 'Miles Morales'),
(68, 'Spider-Gwen'),
(69, 'Spider-Man 2099'),
(70, 'Ironheart'),
(71, 'Moonstone'),
(72, 'Adam Warlock'),
(73, 'Gamora'),
(74, 'Rocket Raccoon'),
(75, 'Groot'),
(76, 'Star-Lord'),
(77, 'Drax'),
(78, 'Mantis'),
(79, 'Deadly Nightshade'),
(80, 'Yellowjacket'),
(81, 'Hank McCoy'),
(82, 'Madrox'),
(83, 'Moira MacTaggert'),
(84, 'Archangel'),
(85, 'Sabretooth'),
(86, 'Mystique'),
(87, 'Omega Red'),
(88, 'Lady Deathstrike'),
(89, 'Juggernaut'),
(90, 'Pyro'),
(91, 'Toad'),
(92, 'Blob'),
(93, 'Aurora'),
(94, 'Northstar');